apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: quroeyndz-python 
  janus-idp.io/tekton: quroeyndz-python
  backstage.io/kubernetes-id: quroeyndz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: quroeyndz-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml